apiVersion: v1
kind: Service
metadata:
  name: turing-modelserver
spec:
  type: ClusterIP
  selector:
    app: turing-serving
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
    - name: zmq-pub
      port: 5556
      targetPort: 5556
      protocol: TCP
    - name: zmq-replay
      port: 5559
      targetPort: 5559
      protocol: TCP
