apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: turing-modelserver
    patch: |-
      - op: replace
        path: /spec/template/metadata/labels/llm-d.ai~1role
        value: prefill-decode
