"""
Concurrency-Adaptive Speculation Gating and Byte-Deterministic Parity Verifier.

Implements dynamic speculation throttling and a spec==plain byte-exact correctness gate.
Based on memra's measurements: speculative decoding delivers 1.82x speedup at c=1 
but hurts at c>=4 due to serial verify contention.
"""
from enum import Enum
from dataclasses import dataclass
from typing import List, Optional, Dict, Any


__all__ = [
    "SpecGateDecision",
    "SpeculationGatePolicy",
    "ParityReport",
    "SpecExactParityVerifier",
]


class SpecGateDecision(Enum):
    """Decisions for speculative decoding tree widths."""
    FULL_SPEC = 'full_spec'
    COLLAPSED = 'collapsed'
    PLAIN = 'plain'


class SpeculationGatePolicy:
    """
    Dynamically throttles speculative decoding based on active session count.
    """
    def __init__(
        self,
        low_threshold: int = 2,
        high_threshold: int = 4,
        default_tree_width: int = 8,
        collapsed_tree_width: int = 2
    ):
        self.low_threshold = low_threshold
        self.high_threshold = high_threshold
        self.default_tree_width = default_tree_width
        self.collapsed_tree_width = collapsed_tree_width
        
        self._current_mode: SpecGateDecision = SpecGateDecision.FULL_SPEC
        self._demotions: int = 0
        self._promotions: int = 0

    def gate_decision(self, active_sessions: int) -> SpecGateDecision:
        """Determines the speculation mode based on active sessions."""
        if active_sessions <= self.low_threshold:
            if self._current_mode != SpecGateDecision.FULL_SPEC:
                self._promotions += 1
            self._current_mode = SpecGateDecision.FULL_SPEC
        elif active_sessions >= self.high_threshold:
            if self._current_mode != SpecGateDecision.PLAIN:
                self._demotions += 1
            self._current_mode = SpecGateDecision.PLAIN
        
        return self._current_mode

    def tree_width(self) -> int:
        """Returns the current tree width based on mode."""
        if self._current_mode == SpecGateDecision.FULL_SPEC:
            return self.default_tree_width
        elif self._current_mode == SpecGateDecision.COLLAPSED:
            return self.collapsed_tree_width
        return 0

    @property
    def stats(self) -> Dict[str, Any]:
        """Returns statistics of the gating policy."""
        return {
            "current_mode": self._current_mode.value,
            "demotions": self._demotions,
            "promotions": self._promotions,
            "tree_width": self.tree_width(),
        }


@dataclass
class ParityReport:
    """Report generated by Parity Verifier."""
    passed: bool
    num_tokens_compared: int
    divergence_index: Optional[int] = None
    spec_tokens: Optional[List[int]] = None
    plain_tokens: Optional[List[int]] = None


class SpecExactParityVerifier:
    """
    Verifies that speculative decoding produces byte-identical output to plain 
    autoregressive decode under greedy conditions.
    """
    
    @staticmethod
    def verify_greedy_parity(spec_tokens: List[int], plain_tokens: List[int]) -> ParityReport:
        """Compares two sets of tokens to verify strict equality."""
        min_len = min(len(spec_tokens), len(plain_tokens))
        
        for i in range(min_len):
            if spec_tokens[i] != plain_tokens[i]:
                return ParityReport(
                    passed=False,
                    num_tokens_compared=i + 1,
                    divergence_index=i,
                    spec_tokens=spec_tokens,
                    plain_tokens=plain_tokens
                )
                
        if len(spec_tokens) != len(plain_tokens):
            return ParityReport(
                passed=False,
                num_tokens_compared=min_len,
                divergence_index=min_len,
                spec_tokens=spec_tokens,
                plain_tokens=plain_tokens
            )

        return ParityReport(
            passed=True,
            num_tokens_compared=len(spec_tokens)
        )

    @staticmethod
    def verify_batch_parity(spec_results: List[List[int]], plain_results: List[List[int]]) -> List[ParityReport]:
        """Verifies parity across a batch of results."""
        return [
            SpecExactParityVerifier.verify_greedy_parity(spec, plain)
            for spec, plain in zip(spec_results, plain_results)
        ]
